"""Remove hashed_password column in site table

Revision ID: 1246ab4e23cc
Revises: 203d569f1ac3
Create Date: 2025-05-27 15:11:16.085295

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1246ab4e23cc'
down_revision = '203d569f1ac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'username')
    op.drop_column('site', 'hashed_password')
    op.drop_column('site', 'password')
    op.drop_column('site', 'port')
    op.drop_column('site', 'ip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('ip', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('site', sa.Column('port', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('site', sa.Column('password', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.add_column('site', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('site', sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
