"""Add ping_hub_interval in site table

Revision ID: 7e281294319b
Revises: 00acc7eb42e5
Create Date: 2025-05-28 11:09:11.914167

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7e281294319b'
down_revision = '00acc7eb42e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('ping_hub_interval', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'ping_hub_interval')
    # ### end Alembic commands ###
