"""Fix wrong locate ping_hub_interval column

Revision ID: 8d627ba76344
Revises: 7e281294319b
Create Date: 2025-05-28 13:25:33.111864

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8d627ba76344'
down_revision = '7e281294319b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hub', sa.Column('ping_hub_interval', sa.Integer(), nullable=False))
    op.drop_column('site', 'ping_hub_interval')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('ping_hub_interval', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('hub', 'ping_hub_interval')
    # ### end Alembic commands ###
