"""Rename column title to name in an item table

Revision ID: c0caa3947cd0
Revises: 1a31ce608336
Create Date: 2025-05-27 11:36:38.167259

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c0caa3947cd0'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.drop_column('item', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('item', 'name')
    # ### end Alembic commands ###
